# Swiftfire Admin module document generator jazzy settings

copyright: Copyright 2016-2020 rien@balancingrock.nl
author: Balancingrock
module: Admin
min_acl: internal
documentation: docs/admin/*.md
readme: docs/admin/Purpose.md
hide_documentation_coverage: true
xcodebuild_arguments: [-target, Swiftfire]
github_url: https://github.com/Balancingrock/Swiftfire
output: ~/Documents/Websites/swiftfire.nl/projects/admin/reference
clean: true
theme: fullwidth
