# Swiftfire Core module document generator jazzy settings

copyright: Copyright 2016-2020 rien@balancingrock.nl
author: Balancingrock
module: Core
min_acl: internal
documentation: docs/core/*.md
readme: docs/core/Purpose.md
hide_documentation_coverage: true
xcodebuild_arguments: [-target, Swiftfire]
github_url: https://github.com/Balancingrock/Swiftfire
output: ~/Documents/Websites/swiftfire.nl/projects/core/reference
clean: true
theme: fullwidth
