# Swiftfire Services module document generator jazzy settings

copyright: Copyright 2016-2020 rien@balancingrock.nl
author: Balancingrock
module: Services
min_acl: internal
readme: docs/services/Purpose.md
documentation: docs/services/*.md
hide_documentation_coverage: false
xcodebuild_arguments: [-target, Swiftfire]
github_url: https://github.com/Balancingrock/Swiftfire
output: ~/Documents/Websites/swiftfire.nl/projects/services/reference
clean: true
theme: fullwidth
